version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: erp
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:example@db:5432/erp'
      JWT_SECRET: 'cambiame_supersecreto'
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db_data:
